### PR TITLE
Ci cd

### LINKED ISSUE #64: automatic update pypi by new release
The package on [pypi](https://pypi.org/) should be updated when a new release is released. You need a key from Lukas for this

### PR DESCRIPTION
**Pull request by glencoe**
Adds automatic version bumping based on commit messages and automatic publishing of the package. This means we need to stick to the following commit message pattern from now on

https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

closes #64

### CODE REVIEW

**Comment by julianhoever** [comment]
@glencoe I am not sure if this is correct, the Bump Version and Release (Semantic Release) Workflow fails for me with this error message:
```
Building elasticai.creator (0.3.8)
  - Building sdist
  - Built elasticai.creator-0.3.8.tar.gz
  - Building wheel
  - Built elasticai.creator-0.3.8-py3-none-any.whl
Uploading to artifact Repository
debug: _handle_credentials_init(ArtifactRepo(repository_name='pypi', repository_url=None, dists=[]))
error: Missing credentials for uploading to artifact repository
```
It looks like there missing credentials for the PyPi repo?

And as I understood what changed now, is that we need to write commit messages in the form of `<type>(<scope>): <subject>`
and it increases automatically the version number and publishes to the PyPi repo. Is this correct or is there a misunderstanding here?

**Comment by julianhoever** [comment]
@glencoe For example to set up the pre-commit stuff I need to have pre-commit installed (https://pre-commit.com/) and run `pre-commit install`. Is this correct? And what else need to be set up or take care of while developing? What is with isort? Is this automatically installed by pre-commit?

**Comment by glencoe** [comment]
@julianhoever had to create the pr to test some of the workflows... It is not yet finished, and i'll add the corresponding documentation

**Comment by julianhoever** [comment]
@glencoe Okay. Thank you

**Pull request merged**
